# Generated by Django 5.2.1 on 2025-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_employee",
            field=models.BooleanField(default=True),
        ),
    ]
